---
title: "LSK Library Prep for Whole Genome"
author: "Alicia M. Rich, Ph.D."
date: "`r Sys.Date()`"
output: 
  html_document:
    theme:
      bootswatch: yeti
runtime: shiny
params:
  local: "/Users/aliciamrich/RStudioMacbook/GitRepos/richlab_main/"
  laptop: "/Users/aliciamrich/RStudioMacbook/GitRepos/richlab_main/"
  desktop: "/Users/arich/Library/CloudStorage/GoogleDrive-aliciamrich@gmail.com/Other computers/My MacBook Pro/RStudioMacbook/GitRepos/richlab_main/"
  
---

```{r global, include=F}
params <- list(
  local = "/Users/aliciamrich/RStudioMacbook/GitRepos/richlab_main/",
  laptop = "/Users/aliciamrich/RStudioMacbook/GitRepos/richlab_main/",
  desktop = "/Users/arich/Library/CloudStorage/GoogleDrive-aliciamrich@gmail.com/Other computers/My MacBook Pro/RStudioMacbook/GitRepos/richlab_main/"
)

source(paste0(params$local, "dependencies/setup.R"))
opts_chunk$set(message = FALSE,
               warning = FALSE,
               echo    = FALSE,
               include = TRUE,
               eval    = TRUE)
```


```{r global, include=F}
source(paste0(params$local, "protocols/builds/Build_Protocol_SQK_LSK114.R"))

```

```{r}
overview <- accordion(open = F,
        accordion_panel(title = "Protocol Overview",
          card(navset_card_tab( 
                nav_panel("Equipment and Materials", 
                          gt_output(outputId = "supplies_all")), 
                nav_panel( "Input DNA", 
                           gt_output(outputId = "input_dna")), 
                nav_panel("SQK-LSK114 Contents", 
                          layout_columns(col_widths = c(4, 8), 
                                         full_screen = T,
                          card(gt_output(outputId = "kit_contents")), 
                          card(imageOutput("LSK114_tubes")))))
              )))

opener <- nav_panel("Setup", value = "start_page",
      overview,
      card(
        card_header("Context"),
        layout_column_wrap(
          dateInput("exp_date", "Start Date", value = Sys.Date(), format = "yyyy-mm-dd"),
          selectInput("author", "Your Name", lab.members),
          selectizeInput("assist", "Others Assisting", lab.members, multiple = T, selected = "NA"))),
      card(
        card_header("Equipment/Consumables"),
        layout_column_wrap(
          selectInput("flowcell_type", "Flow Cell Type", choices = c("Flongle", "MinION", "PromethION")),
          textInput("flowcell_num", "Flow Cell Serial Num", value = "SERIAL")),
          selectInput("minion", "Device Name", choices = c("Angel", "Spike"))),
      card(
        card_header("Calculating Input Amounts"),
        layout_column_wrap(
          radioButtons("strands", "DNA Type", choices = list("dsDNA (nuclear DNA)" = 2, "ssDNA (mtDNA)" = 1), selected = 2),
          radioButtons("fragments", "Input Length", choices = input_options, selected = 1),
          uiOutput("adjust_length")),
        card_footer(uiOutput("adjust_input"))),
      card(
        card_header("Select samples to include"),
          reactableOutput("samples"),
          textOutput("selected")),
      textAreaInput("start_note", "Notes/Comments (Optional)"),
      actionButton("submit_start_note", label = "Enter note"),
      textOutput("start_note_submitted"),
      card_footer(actionButton("setup_done", "Next: Begin Protocol")))

endprep.tab <- nav_panel("I. DNA Repair and End Prep", value = "endprep",
      card(
        card_header("I. DNA Repair and End Prep"),
          accordion(open = F, 
                    accordion_panel("Materials", gt_output(outputId = "supplies_endprep")), endprep.recs,
                    accordion_panel("Working Samples and Dilutions", reactableOutput("filtered_table"),)),
          make_steps(endprep),
        card_footer(actionButton("endprep_done", "Next: Adapter Ligation"))))

adapter.tab <- nav_panel("II. Adapter Ligation", value = "adapter",
      card(
        card_header("II. Adapter Ligation"),
          accordion(open = F, accordion_panel("Materials", gt_output(outputId = "supplies_adapter")), adapter.recs),
          make_steps(adapter),
        card_footer(actionButton("adapter_done", "Next: Library Cleanup"))))

cleanup.tab <- nav_panel("III. Library Clean-up", value = "cleanup",
      card(
        card_header("III. Library Clean-up"),
          accordion(open = F, accordion_panel("Materials", gt_output(outputId = "supplies_cleanup"))),
          make_steps(cleanup),
      card_footer(actionButton("cleanup_done", "Next: Prime/Load Flow Cell"))))

flowcell.tab <- nav_panel("IV. Prime and Load Flow Cell", value = "flowcell",
       card(
         card_header("IV. Prime and Load Flow Cell"),
          accordion(open = F, accordion_panel("Materials", gt_output(outputId = "supplies_flowcell")), flowcell.recs),
          make_steps(flowcell),
         card_footer(actionButton("flowcell_done", "Next: Complete Experiment"))))

conclude <- nav_panel("Conclude", value = "closer",
        card(card_header("Notebook Entry Conclusion"),
          tags$h2("Before you finish:"), tags$br(),
          tags$h4("Conclude your notebook entry and export report..."), tags$br(),
          dateInput("exp_date", "End Date", value = Sys.Date(), format = "yyyy-mm-dd"),
          textAreaInput("end_note", "Notes/Comments"),
          textOutput("end_note_render"),
          actionButton("generate_report", label = "Generate Report"),
          textOutput("report_preview"),
        card_footer(downloadButton("download_report", "Download Report")))
)

ui <- page_fillable(
  useShinyjs(),
  navset_tab(id = "main.nav", opener,
        nav_menu("Protocol Steps",
                  endprep.tab, 
                  adapter.tab, 
                  cleanup.tab, 
                  flowcell.tab),
                  conclude))
```


```{r, context = "server"}
server <- function(input, output, session) {
  
session$setCurrentTheme(bs_theme(bootswatch = "lumen"))
  
  source(paste0(params$local, "protocols/builds/server_cards_SQK_LSK114.R"    ), local = TRUE)
  source(paste0(params$local, "protocols/builds/server_reactable_SQK_LSK114.R"), local = TRUE)
  source(paste0(params$local, "protocols/builds/server_images_SQK_LSK114.R"   ), local = TRUE)
  source(paste0(params$local, "protocols/builds/server_reactive_SQK_LSK114.R" ), local = TRUE)
  source(paste0(params$local, "protocols/builds/server_ui_SQK_LSK114.R"       ), local = TRUE)

  selected <- reactive(getReactableState("samples", "selected"))

output$selected <- renderPrint({
  validate(need(!is.null(selected()), "No rows selected."))
  selected()
})

selected_samples <- reactive({
  req(selected(), 
      input$input_confirmed, 
      input$author, 
      input$exp_date, 
      input$flowcell_type, 
      input$flowcell_num, 
      input$minion, 
      input$fragments, 
      input$fragment_length)
  samples.loris[selected(), ] %>%
    select(
      SampleID,
      ExtractID_DNA,
      ExtractConc_DNA
    ) %>%
    mutate(TubeNo                = row_number(),
           InputMassStart        = input$input_confirmed,
           LibPrepBy             = input$author,
           LibPrepDate           = input$exp_date,
           FlowCellType          = input$flowcell_type,
           FlowCellSerial        = input$flowcell_num,
           SeqDevice             = input$minion,
           AdjLength             = input$fragment_length,
           Strands               = as.numeric(input$strands)) %>%
    mutate(
      ExtractInputVol       = if_else(
        (InputMassStart/ExtractConc_DNA) >= 47, 47,
        InputMassStart/ExtractConc_DNA),
      InputMassFinal  = case_when(
        input$fragments == "1" ~ 300,
        input$fragments == "2" ~ (50 * ((AdjLength * (307.97*Strands)) + (18.02*Strands)) * 10^-6),
        input$fragments == "3" ~ (45 * ((AdjLength * (307.97*Strands)) + (18.02*Strands)) * 10^-6),
        input$fragments == "4" ~ (35 * ((AdjLength * (307.97*Strands)) + (18.02*Strands)) * 10^-6),
        input$fragments == "5" ~ 300)) %>%
    mutate(ExtractDiluteWater = 47 - ExtractInputVol)
})

working_samples <- reactive({
  req(selected_samples(), QC_df())
  selected_samples() %>%
    left_join(QC_df()) %>%
    mutate(AdjustLibrary  = case_when(
      InputMassFinal/Conc_QC2 == 12 ~ "None",
      InputMassFinal/Conc_QC2  > 12 ~ "Enrich",
      InputMassFinal/Conc_QC2  < 12 ~ "Dilute")) %>%
    mutate(LibraryLoadingVol  = if_else(
      InputMassFinal/Conc_QC2 >= 12, 12,
      InputMassFinal/Conc_QC2)) %>%
    mutate(LibraryWaterVol = 12 - LibraryLoadingVol)
})
  
}
```

```{r}
shinyApp(ui = ui, server = server)
```
