---
title: "LSK Library Prep for Whole Genome"
author: "Alicia M. Rich, Ph.D."
date: "`r Sys.Date()`"
output: 
  html_document:
    theme:
      bootswatch: sandstone
    css: "/Users/aliciamrich/RStudioMacbook/GitRepos/richlab_main/dependencies/_bootswatch.scss"
runtime: shiny
params:
  local: "/Users/aliciamrich/RStudioMacbook/GitRepos/richlab_main/"
  laptop: "/Users/aliciamrich/RStudioMacbook/GitRepos/richlab_main/"
  desktop: "/Users/arich/Library/CloudStorage/GoogleDrive-aliciamrich@gmail.com/Other computers/My MacBook Pro/RStudioMacbook/GitRepos/richlab_main/"
  
---

```{r global, include=F}
params <- list(
  local = "/Users/aliciamrich/RStudioMacbook/GitRepos/richlab_main/",
  laptop = "/Users/aliciamrich/RStudioMacbook/GitRepos/richlab_main/",
  desktop = "/Users/arich/Library/CloudStorage/GoogleDrive-aliciamrich@gmail.com/Other computers/My MacBook Pro/RStudioMacbook/GitRepos/richlab_main/"
)

source(paste0(params$local, "dependencies/setup.R"))
opts_chunk$set(message = FALSE,
               warning = FALSE,
               echo    = FALSE,
               include = TRUE,
               eval    = TRUE)
source(paste0(params$local, "protocols/builds/Build_Protocol_SQK_LSK114.R"))

bs_global_theme(bootswatch = "sandstone")
```


```{r}
create_step <- function(step_id, description, additional_ui = NULL) {
  layout_columns(
    col_widths = c(1, 11),
    checkboxInput(inputId = paste0(step_id, "_check"), label = ""),
    tags$li(
      description,
      input_switch(id = paste0("annotate_", step_id), label = "Add annotation"),
      uiOutput(outputId = paste0("text_", step_id)),
      uiOutput(outputId = paste0("submit_", step_id)),
      uiOutput(outputId = paste0("annotation_", step_id)),
      additional_ui))
}
```

```{r}
create_step <- function(step_id, description, additional_ui)
```


```{r}
steps %>% filter(stage == "endprep") %>%
map(list(step_id) ~ )
```


```{r}
end2_substeps <- tags$ol(
      tags$li("Thaw all reagents on ice."),
      tags$li("Flick and/or invert the reagent tubes to ensure they are well mixed.", br(),
              "Note: Do not vortex the FFPE DNA Repair Mix or Ultra II End Prep Enzyme Mix."),
      tags$li("Always spin down tubes before opening for the first time each day."),
      tags$li("Vortex the FFPE DNA Repair Buffer v2, or the NEBNext FFPE DNA Repair Buffer and Ultra II End Prep Reaction Buffer to ensure they are well mixed.", br(),
              "Note: These buffers may contain a white precipitate. If this occurs, allow the mixture(s) to come to room temperature and pipette the buffer several times to break up the precipitate, followed by a quick vortex to mix."),
      tags$li("The FFPE DNA Repair Buffer may have a yellow tinge and is fine to use if yellow."))

end3_substeps <- tags$ol(
      tags$li("Transfer 1 μg (or 100-200 fmol) input DNA into a 1.5 ml Eppendorf DNA LoBind tube."),
      tags$li("Adjust the volume to 47 μl with nuclease-free water."),
      tags$li("Mix thoroughly by pipetting up and down, or by flicking the tube."),
      tags$li("Spin down briefly in a microfuge.")
    )
```

```{r}
substeps <- bind_rows(
  tibble(
    description = "Prepare the NEB reagents in accordance with manufacturer’s instructions, and place on ice.",
    substep = c(
      "Thaw all reagents on ice.",
      "Flick and/or invert the reagent tubes to ensure they are well mixed. Do not vortex the FFPE DNA Repair Mix or Ultra II End Prep Enzyme Mix.",
      "Always spin down tubes before opening for the first time each day.",
      "Vortex the FFPE DNA Repair Buffer v2, or the NEBNext FFPE DNA Repair Buffer and Ultra II End Prep Reaction Buffer to ensure they are well mixed.",
      "The FFPE DNA Repair Buffer may have a yellow tinge and is fine to use if yellow.")),
  tibble(
    description = "Prepare the DNA in nuclease-free water.",
    substep = c(
      "Transfer 1 μg (or 100-200 fmol) input DNA into a 1.5 ml Eppendorf DNA LoBind tube.",
      "Adjust the volume to 47 μl with nuclease-free water.",
      "Mix thoroughly by pipetting up and down, or by flicking the tube.",
      "Spin down briefly in a microfuge.")),
  tibble(
    description = "After opening the priming port, check for a small air bubble under the cover. Draw back a small volume to remove any bubbles.",
    substep = c(
      "Set a P1000 pipette to 200 µl",
      "Insert the tip into the priming port",
      "Turn the wheel until the dial shows 220-230 µl, to draw back 20-30 µl, or until you can see a small volume of buffer entering the pipette tip")),
  tibble(
    description = "Complete the flow cell priming.",
    substep = c(
      "Gently lift the SpotON sample port cover to make the SpotON sample port accessible.",
      "Load 200 µl of the priming mix into the flow cell priming port (not the SpotON sample port), avoiding the introduction of air bubbles.")),
  tibble(
    description = "Place the light shield onto the flow cell.",
    substep = c(
      "Carefully place the leading edge of the light shield against the clip. Note: Do not force the light shield underneath the clip.",
      "Gently lower the light shield onto the flow cell. The light shield should sit around the SpotON cover, covering the entire top section of the flow cell."))
) %>%
  group_by(description) %>%
  mutate(substep_order = row_number())
```

```{r}
steps <- list(
"endprep" = 
  list(
    "Thaw DNA Control Sample (DCS) at room temperature, spin down, mix by pipetting, and place on ice.",
    "Prepare the NEB reagents in accordance with manufacturer’s instructions, and place on ice." = 
  list("Thaw all reagents on ice.",
       "Flick and/or invert the reagent tubes to ensure they are well mixed. Do not vortex the FFPE DNA Repair Mix or Ultra II End Prep Enzyme Mix.",
       "Always spin down tubes before opening for the first time each day.",
       "Vortex the FFPE DNA Repair Buffer v2, or the NEBNext FFPE DNA Repair Buffer and Ultra II End Prep Reaction Buffer to ensure they are well mixed.",
       "The FFPE DNA Repair Buffer may have a yellow tinge and is fine to use if yellow."),
    "Prepare the DNA in nuclease-free water." = 
  list("Transfer 1 μg (or 100-200 fmol) input DNA into a 1.5 ml Eppendorf DNA LoBind tube.",
       "Adjust the volume to 47 μl with nuclease-free water.",
       "Mix thoroughly by pipetting up and down, or by flicking the tube.",
       "Spin down briefly in a microfuge."),
    "In a 0.2 ml thin-walled PCR tube, prepare the reaction mix.",
    "Thoroughly mix the reaction by gently pipetting and briefly spinning down.",
    "Using a thermal cycler, incubate at 20°C for 5 minutes and 65°C for 5 minutes.",
    "Resuspend the AMPure XP Beads (AXP) by vortexing.",
    "Transfer the DNA sample to a clean 1.5 ml Eppendorf DNA LoBind tube.",
    "Add 60 µl of resuspended the AMPure XP Beads (AXP) to the end-prep reaction and mix by flicking the tube.",
    "Incubate on a Hula mixer (rotator mixer) for 5 minutes at room temperature.",
    "Prepare 500 μl of fresh 80% ethanol in nuclease-free water.",
    "Spin down the sample and pellet on a magnet until supernatant is clear and colourless. Keep the tube on the magnet, and pipette off the supernatant.",
    "Keep the tube on the magnet and wash the beads with 200 µl of freshly prepared 80% ethanol without disturbing the pellet. Remove the ethanol using a pipette and discard.",
    "Repeat the previous step.",
    "Spin down and place the tube back on the magnet. Pipette off any residual ethanol. Allow to dry for ~30 seconds, but do not dry the pellet to the point of cracking.",
    "Remove the tube from the magnetic rack and resuspend the pellet in 61 µl nuclease-free water. Incubate for 2 minutes at room temperature.",
    "Pellet the beads on a magnet until the eluate is clear and colourless, for at least 1 minute.",
    "Remove and retain 61 µl of eluate into a clean 1.5 ml Eppendorf DNA LoBind tube.",
    "Quantify 1 µl of eluted sample using a Qubit fluorometer."),
"adapter" = 
  list(
  "Spin down the Ligation Adapter (LA) and Salt-T4® DNA Ligase, and place on ice.",
  "Thaw Ligation Buffer (LNB) at room temperature, spin down and mix by pipetting. Due to viscosity, vortexing this buffer is ineffective. Place on ice immediately after thawing and mixing.",
  "Thaw the Elution Buffer (EB) at room temperature and mix by vortexing. Then spin down and place on ice.",
  "Thaw either Long Fragment Buffer (LFB) or Short Fragment Buffer (SFB) at room temperature and mix by vortexing. Then spin down and place on ice.",
  "In a 1.5 ml Eppendorf DNA LoBind tube, prepare the reaction mix.",
  "Thoroughly mix the reaction by gently pipetting and briefly spinning down.",
  "Incubate the reaction for 10 minutes at room temperature."),
"cleanup" = 
  list(
  "Resuspend the AMPure XP Beads (AXP) by vortexing.",
  "Add 40 µl of resuspended AMPure XP Beads (AXP) to the reaction and mix by flicking the tube.",
  "Incubate on a Hula mixer (rotator mixer) for 5 minutes at room temperature.",
  "Spin down the sample and pellet on a magnet. Keep the tube on the magnet, and pipette off the supernatant when clear and colourless.",
  "Wash the beads by adding either 250 μl Long Fragment Buffer (LFB) or 250 μl Short Fragment Buffer (SFB). Flick the beads to resuspend, spin down, then return the tube to the magnetic rack and allow the beads to pellet. Remove the supernatant using a pipette and discard.",
  "Repeat the previous step.",
  "Spin down and place the tube back on the magnet. Pipette off any residual supernatant. Allow to dry for ~30 seconds, but do not dry the pellet to the point of cracking.",
  "Remove the tube from the magnetic rack and resuspend the pellet in 15 µl Elution Buffer (EB). Spin down and incubate for 10 minutes at room temperature. For high molecular weight DNA, incubating at 37°C can improve the recovery of long fragments.",
  "Pellet the beads on a magnet until the eluate is clear and colourless, for at least 1 minute.",
  "Remove and retain 15 µl of eluate containing the DNA library into a clean 1.5 ml Eppendorf DNA LoBind tube. Dispose of the pelleted beads",
  "Quantify 1 µl of eluted sample using a Qubit fluorometer.",
  "Depending on your DNA library fragment size, prepare your final library in 12 µl of Elution Buffer (EB)."),

"flowcell" = 
  list(
  "Thaw the Sequencing Buffer (SB), Library Beads (LIB) or Library Solution (LIS, if using), Flow Cell Tether (FCT) and Flow Cell Flush (FCF) at room temperature before mixing by vortexing. Then spin down and store on ice.",
  "To prepare the flow cell priming mix with BSA, combine Flow Cell Flush (FCF) and Flow Cell Tether (FCT), as directed below. Mix by pipetting at room temperature.",
  "Open the MinION or GridION device lid and slide the flow cell under the clip. Press down firmly on the flow cell to ensure correct thermal and electrical contact.",
  "Slide the flow cell priming port cover clockwise to open the priming port.",
  "After opening the priming port, check for a small air bubble under the cover. Draw back a small volume to remove any bubbles." = 
  list("Set a P1000 pipette to 200 µl",
       "Insert the tip into the priming port",
       "Turn the wheel until the dial shows 220-230 µl, to draw back 20-30 µl, or until you can see a small volume of buffer entering the pipette tip"),
  "Load 800 µl of the priming mix into the flow cell via the priming port, avoiding the introduction of air bubbles. Wait for five minutes. During this time, prepare the library for loading by following the steps below.",
  "Thoroughly mix the contents of the Library Beads (LIB) by pipetting.",
  "In a new 1.5 ml Eppendorf DNA LoBind tube, prepare the flow cell reaction mix.",
  "Complete the flow cell priming." = 
  list("Gently lift the SpotON sample port cover to make the SpotON sample port accessible.",
       "Load 200 µl of the priming mix into the flow cell priming port (not the SpotON sample port), avoiding the introduction of air bubbles."),
  "Mix the prepared library gently by pipetting up and down just prior to loading.",
  "Add 75 μl of the prepared library to the flow cell via the SpotON sample port in a dropwise fashion. Ensure each drop flows into the port before adding the next.",
  "Gently replace the SpotON sample port cover, making sure the bung enters the SpotON port and close the priming port.",
  "Place the light shield onto the flow cell." = 
  list("Carefully place the leading edge of the light shield against the clip. Note: Do not force the light shield underneath the clip.",
       "Gently lower the light shield onto the flow cell. The light shield should sit around the SpotON cover, covering the entire top section of the flow cell."))
)
```


```{r}
substeps <- 
  list(
"Prepare the NEB reagents in accordance with manufacturer’s instructions, and place on ice." = 
  list("Thaw all reagents on ice.",
       "Flick and/or invert the reagent tubes to ensure they are well mixed. Do not vortex the FFPE DNA Repair Mix or Ultra II End Prep Enzyme Mix.",
       "Always spin down tubes before opening for the first time each day.",
       "Vortex the FFPE DNA Repair Buffer v2, or the NEBNext FFPE DNA Repair Buffer and Ultra II End Prep Reaction Buffer to ensure they are well mixed.",
       "The FFPE DNA Repair Buffer may have a yellow tinge and is fine to use if yellow."),
"Prepare the DNA in nuclease-free water." = 
  list("Transfer 1 μg (or 100-200 fmol) input DNA into a 1.5 ml Eppendorf DNA LoBind tube.",
       "Adjust the volume to 47 μl with nuclease-free water.",
       "Mix thoroughly by pipetting up and down, or by flicking the tube.",
       "Spin down briefly in a microfuge."),
"After opening the priming port, check for a small air bubble under the cover. Draw back a small volume to remove any bubbles." = 
  list("Set a P1000 pipette to 200 µl",
       "Insert the tip into the priming port",
       "Turn the wheel until the dial shows 220-230 µl, to draw back 20-30 µl, or until you can see a small volume of buffer entering the pipette tip"),
"Complete the flow cell priming." = 
  list("Gently lift the SpotON sample port cover to make the SpotON sample port accessible.",
       "Load 200 µl of the priming mix into the flow cell priming port (not the SpotON sample port), avoiding the introduction of air bubbles."),
       "Place the light shield onto the flow cell." = 
  list("Carefully place the leading edge of the light shield against the clip. Note: Do not force the light shield underneath the clip.",
       "Gently lower the light shield onto the flow cell. The light shield should sit around the SpotON cover, covering the entire top section of the flow cell.")
)
```



```{r}
steps <- bind_rows(
  tibble(stage = "endprep", description = c(
"Thaw DNA Control Sample (DCS) at room temperature, spin down, mix by pipetting, and place on ice.",
"Prepare the NEB reagents in accordance with manufacturer’s instructions, and place on ice.",
"Prepare the DNA in nuclease-free water.",
"In a 0.2 ml thin-walled PCR tube, prepare the reaction mix.",
"Thoroughly mix the reaction by gently pipetting and briefly spinning down.",
"Using a thermal cycler, incubate at 20°C for 5 minutes and 65°C for 5 minutes.",
"Resuspend the AMPure XP Beads (AXP) by vortexing.",
"Transfer the DNA sample to a clean 1.5 ml Eppendorf DNA LoBind tube.",
"Add 60 µl of resuspended the AMPure XP Beads (AXP) to the end-prep reaction and mix by flicking the tube.",
 "Incubate on a Hula mixer (rotator mixer) for 5 minutes at room temperature.",
 "Prepare 500 μl of fresh 80% ethanol in nuclease-free water.",
 "Spin down the sample and pellet on a magnet until supernatant is clear and colourless. Keep the tube on the magnet, and pipette off the supernatant.",
 "Keep the tube on the magnet and wash the beads with 200 µl of freshly prepared 80% ethanol without disturbing the pellet. Remove the ethanol using a pipette and discard.",
 "Repeat the previous step.",
 "Spin down and place the tube back on the magnet. Pipette off any residual ethanol. Allow to dry for ~30 seconds, but do not dry the pellet to the point of cracking.",
 "Remove the tube from the magnetic rack and resuspend the pellet in 61 µl nuclease-free water. Incubate for 2 minutes at room temperature.",
 "Pellet the beads on a magnet until the eluate is clear and colourless, for at least 1 minute.",
 "Remove and retain 61 µl of eluate into a clean 1.5 ml Eppendorf DNA LoBind tube.",
 "Quantify 1 µl of eluted sample using a Qubit fluorometer.")),

tibble(stage = "adapter" , description = c(
  "Spin down the Ligation Adapter (LA) and Salt-T4® DNA Ligase, and place on ice.",
  "Thaw Ligation Buffer (LNB) at room temperature, spin down and mix by pipetting. Due to viscosity, vortexing this buffer is ineffective. Place on ice immediately after thawing and mixing.",
  "Thaw the Elution Buffer (EB) at room temperature and mix by vortexing. Then spin down and place on ice.",
  "Thaw either Long Fragment Buffer (LFB) or Short Fragment Buffer (SFB) at room temperature and mix by vortexing. Then spin down and place on ice.",
  "In a 1.5 ml Eppendorf DNA LoBind tube, prepare the reaction mix.",
  "Thoroughly mix the reaction by gently pipetting and briefly spinning down.",
  "Incubate the reaction for 10 minutes at room temperature."
  )),
tibble(stage = "cleanup" , description = c(
  "Resuspend the AMPure XP Beads (AXP) by vortexing.",
  "Add 40 µl of resuspended AMPure XP Beads (AXP) to the reaction and mix by flicking the tube.",
  "Incubate on a Hula mixer (rotator mixer) for 5 minutes at room temperature.",
  "Spin down the sample and pellet on a magnet. Keep the tube on the magnet, and pipette off the supernatant when clear and colourless.",
  "Wash the beads by adding either 250 μl Long Fragment Buffer (LFB) or 250 μl Short Fragment Buffer (SFB). Flick the beads to resuspend, spin down, then return the tube to the magnetic rack and allow the beads to pellet. Remove the supernatant using a pipette and discard.",
  "Repeat the previous step.",
  "Spin down and place the tube back on the magnet. Pipette off any residual supernatant. Allow to dry for ~30 seconds, but do not dry the pellet to the point of cracking.",
  "Remove the tube from the magnetic rack and resuspend the pellet in 15 µl Elution Buffer (EB). Spin down and incubate for 10 minutes at room temperature. For high molecular weight DNA, incubating at 37°C can improve the recovery of long fragments.",
  "Pellet the beads on a magnet until the eluate is clear and colourless, for at least 1 minute.",
  "Remove and retain 15 µl of eluate containing the DNA library into a clean 1.5 ml Eppendorf DNA LoBind tube. Dispose of the pelleted beads",
  "Quantify 1 µl of eluted sample using a Qubit fluorometer.",
  "Depending on your DNA library fragment size, prepare your final library in 12 µl of Elution Buffer (EB)."
)),
tibble(stage = "flowcell", description = c(
  "Thaw the Sequencing Buffer (SB), Library Beads (LIB) or Library Solution (LIS, if using), Flow Cell Tether (FCT) and Flow Cell Flush (FCF) at room temperature before mixing by vortexing. Then spin down and store on ice.",
  "To prepare the flow cell priming mix with BSA, combine Flow Cell Flush (FCF) and Flow Cell Tether (FCT), as directed below. Mix by pipetting at room temperature.",
  "Open the MinION or GridION device lid and slide the flow cell under the clip. Press down firmly on the flow cell to ensure correct thermal and electrical contact.",
  "Slide the flow cell priming port cover clockwise to open the priming port.",
  "After opening the priming port, check for a small air bubble under the cover. Draw back a small volume to remove any bubbles.",
  "Load 800 µl of the priming mix into the flow cell via the priming port, avoiding the introduction of air bubbles. Wait for five minutes. During this time, prepare the library for loading by following the steps below.",
  "Thoroughly mix the contents of the Library Beads (LIB) by pipetting.",
  "In a new 1.5 ml Eppendorf DNA LoBind tube, prepare the flow cell reaction mix.",
  "Complete the flow cell priming.",
  "Mix the prepared library gently by pipetting up and down just prior to loading.",
  "Add 75 μl of the prepared library to the flow cell via the SpotON sample port in a dropwise fashion. Ensure each drop flows into the port before adding the next.",
  "Gently replace the SpotON sample port cover, making sure the bung enters the SpotON port and close the priming port.",
  "Place the light shield onto the flow cell (see below)."
))
) %>%
  mutate(step_id = paste0("step", row_number())) %>%
  left_join(substeps) %>%
  group_by(stage, step_id, description) %>%
  nest(.key = "substeps")
```





```{r}
end_steps <- list(
  create_step("step1", "Thaw DNA Control Sample (DCS) at room temperature, spin down, mix by pipetting, and place on ice."),
  create_step("step2", "Prepare the NEB reagents in accordance with manufacturer’s instructions, and place on ice.", additional_ui = end2_substeps),
  create_step("step3", "Prepare the DNA in nuclease-free water.", additional_ui = end3_substeps),
  create_step("step4", "In a 0.2 ml thin-walled PCR tube, prepare the reaction mix.", gt_output("endprep_mix")),
  create_step("step5", "Thoroughly mix the reaction by gently pipetting and briefly spinning down."),
  create_step("step6", "Using a thermal cycler, incubate at 20°C for 5 minutes and 65°C for 5 minutes."),
  create_step("step7", "Resuspend the AMPure XP Beads (AXP) by vortexing."),
  create_step("step8", "Transfer the DNA sample to a clean 1.5 ml Eppendorf DNA LoBind tube."),
  create_step("step9", "Add 60 µl of resuspended the AMPure XP Beads (AXP) to the end-prep reaction and mix by flicking the tube."),
  create_step("step10", "Incubate on a Hula mixer (rotator mixer) for 5 minutes at room temperature."),
  create_step("step11", "Prepare 500 μl of fresh 80% ethanol in nuclease-free water."),
  create_step("step12", "Spin down the sample and pellet on a magnet until supernatant is clear and colourless. Keep the tube on the magnet, and pipette off the supernatant."),
  create_step("step13", "Keep the tube on the magnet and wash the beads with 200 µl of freshly prepared 80% ethanol without disturbing the pellet. Remove the ethanol using a pipette and discard."),
  create_step("step14", "Repeat the previous step."),
  create_step("step15", "Spin down and place the tube back on the magnet. Pipette off any residual ethanol. Allow to dry for ~30 seconds, but do not dry the pellet to the point of cracking."),
  create_step("step16", "Remove the tube from the magnetic rack and resuspend the pellet in 61 µl nuclease-free water. Incubate for 2 minutes at room temperature."),
  create_step("step17", "Pellet the beads on a magnet until the eluate is clear and colourless, for at least 1 minute."),
  create_step("step18", "Remove and retain 61 µl of eluate into a clean 1.5 ml Eppendorf DNA LoBind tube."),
  create_step("step19", "Quantify 1 µl of eluted sample using a Qubit fluorometer.")
)

endprep_steps <- card(tags$ol(end_steps))
```

```{r}
adapt_steps <- list(
create_step("step20", "Spin down the Ligation Adapter (LA) and Salt-T4® DNA Ligase, and place on ice."),
create_step("step21", "Thaw Ligation Buffer (LNB) at room temperature, spin down and mix by pipetting. Due to viscosity, vortexing this buffer is ineffective. Place on ice immediately after thawing and mixing."),
create_step("step22", "Thaw the Elution Buffer (EB) at room temperature and mix by vortexing. Then spin down and place on ice."),
create_step("step23", "Thaw either Long Fragment Buffer (LFB) or Short Fragment Buffer (SFB) at room temperature and mix by vortexing. Then spin down and place on ice."),
create_step("step24", "In a 1.5 ml Eppendorf DNA LoBind tube, prepare the reaction mix.", gt_output("rxn_adapter")),
create_step("step25", "Thoroughly mix the reaction by gently pipetting and briefly spinning down."),
create_step("step26", "Incubate the reaction for 10 minutes at room temperature.")
)

adapter_steps <- card(tags$ol(adapt_steps))

```

```{r}
clean_steps <- list(
create_step("step27", "Resuspend the AMPure XP Beads (AXP) by vortexing."),
create_step("step28", "Add 40 µl of resuspended AMPure XP Beads (AXP) to the reaction and mix by flicking the tube."),
create_step("step29", "Incubate on a Hula mixer (rotator mixer) for 5 minutes at room temperature."),
create_step("step30", "Spin down the sample and pellet on a magnet. Keep the tube on the magnet, and pipette off the supernatant when clear and colourless."),
create_step("step31", "Wash the beads by adding either 250 μl Long Fragment Buffer (LFB) or 250 μl Short Fragment Buffer (SFB). Flick the beads to resuspend, spin down, then return the tube to the magnetic rack and allow the beads to pellet. Remove the supernatant using a pipette and discard."),
create_step("step32", "Repeat the previous step."),
create_step("step33", "Spin down and place the tube back on the magnet. Pipette off any residual supernatant. Allow to dry for ~30 seconds, but do not dry the pellet to the point of cracking."),
create_step("step34", "Remove the tube from the magnetic rack and resuspend the pellet in 15 µl Elution Buffer (EB). Spin down and incubate for 10 minutes at room temperature. For high molecular weight DNA, incubating at 37°C can improve the recovery of long fragments."),
create_step("step35", "Pellet the beads on a magnet until the eluate is clear and colourless, for at least 1 minute."),
create_step("step36", "Remove and retain 15 µl of eluate containing the DNA library into a clean 1.5 ml Eppendorf DNA LoBind tube. Dispose of the pelleted beads"),
create_step("step37", "Quantify 1 µl of eluted sample using a Qubit fluorometer."),
create_step("step38", "Depending on your DNA library fragment size, prepare your final library in 12 µl of Elution Buffer (EB).")
)

cleanup_steps <- card(tags$ol(clean_steps))

```

```{r}
overview.tab <- page_fillable(
  navset_card_tab( 
    nav_panel("Equipment and Materials", gt_output(outputId = "supplies_all")), 
    nav_panel( "Input DNA", gt_output(outputId = "input_dna")), 
    nav_panel("SQK-LSK114 Contents", layout_columns( 
              card(gt_output(outputId = "kit_contents")), card(imageOutput("LSK114_tubes")), 
        col_widths = c(4, 8))),
    full_screen = T
  )
)
```

```{r}
endprep.recs <- nav_panel("Recommendations", 
      card(class = "bg-info",
      card_header("Tip from ONT"),
      card_body("ONT recommends using the NEBNext® Companion Module v2 for Oxford Nanopore Technologies® Ligation Sequencing (E7672S/E7672L), which contains all the NEB reagents needed for use with the Ligation Sequencing Kit."),
      card_footer("The previous version, NEBNext® Companion Module for Oxford Nanopore Technologies® Ligation Sequencing (NEB, E7180S/E7180L) is also compatible, but the recommended v2 module offers more efficient dA-tailing and ligation.")), 
      card(class = "bg-info",
      card_header("Tip from ONT"),
      card_body("ONT recommends using the DNA Control Sample (DCS) in your library prep for troubleshooting purposes."),
      card_footer("You can also omit this step and make up the extra 1 µl with your sample DNA, if preferred.")), 
      card(class = "bg-primary",
      card_header("Check your flow cell."),
      card_body("You should perform a flow cell check before starting your library prep to ensure you have a flow cell with enough pores for a good sequencing run.",
      accordion(open = FALSE, accordion_panel(title = "Flow Cell Guidelines", gt_output("flowcell_check"))))))
```

```{r}
adapter.recs <- nav_panel("Recommendations", 
      card(class = "bg-info",
      card_header("Tip from ONT"),
      card_body("ONT recommends using the  the Salt-T4® DNA Ligase (NEB, M0467)"),
      card_footer("Salt-T4® DNA Ligase (NEB, M0467) can be bought separately or is provided in the NEBNext® Companion Module v2 for Oxford Nanopore Technologies® Ligation Sequencing (E7672S/E7672L).", br(), "The Quick T4 DNA Ligase (NEB, E6057) available in the previous version NEBNext® Companion Module for Oxford Nanopore Technologies® Ligation Sequencing (NEB, E7180S/E7180L) is also compatible, but the new recommended reagent offers more efficient and ligation.")),
      card(class = "bg-warning",
      card_header("IMPORTANT"),
      card_body("Although third-party ligase products may be supplied with their own buffer, the ligation efficiency of the Ligation Adapter (LA) is higher when using the Ligation Buffer (LNB) supplied in the Ligation Sequencing Kit.")),
      card(class = "bg-warning",
      card_header("IMPORTANT"),
      card_body("Depending on the wash buffer (LFB or SFB) used, the clean-up step after adapter ligation is designed to either enrich for DNA fragments of >3 kb, or purify all fragments equally."),
      card_footer(
      tags$ul(
        tags$li("To enrich for DNA fragments of 3 kb or longer, use Long Fragment Buffer (LFB)"),
        tags$li("To retain DNA fragments of all sizes, use Short Fragment Buffer (SFB)")))))
```



```{r}
endprep.tab <- page_fillable(
  navset_card_tab( 
    nav_panel("Materials", gt_output(outputId = "supplies_endprep")), 
    endprep.recs, 
    nav_panel("Procedure", endprep_steps))
)
```

```{r}
adapter.tab <- page_fillable(
  navset_card_tab( 
    nav_panel("Materials", gt_output(outputId = "supplies_adapter")), 
    adapter.recs,
    nav_panel("Procedure", adapter_steps))
)
```

```{r}
cleanup.tab <- page_fillable(cleanup_steps)
```


```{r}
ui <- page_fillable(
  navset_tab(
    nav_panel("Overview"                    ,  overview.tab ), 
    nav_panel("DNA Repair and End Prep"     ,  endprep.tab  ), 
    nav_panel("Adapter Ligation"            ,  adapter.tab  ), 
    nav_panel("Library Clean-up"            ,  cleanup.tab  ), 
    nav_panel("Prime and Load Flow Cell"    , "flowcell.tab" ), 
    id = "lsk114_protocol"),
  theme = bs_theme(bootswatch = "sandstone")
)
```

```{r, context = "server"}
server <- function(input, output) {
  output$supplies_all      <- render_gt(expr = gt_supplies)
  output$supplies_endprep  <- render_gt(expr = supplies_endprep)
  output$supplies_adapter  <- render_gt(expr = supplies_adapter)
  output$supplies_cleanup  <- render_gt(expr = supplies_cleanup)
  output$supplies_flowcell <- render_gt(expr = supplies_flowcell)
  output$input_dna         <- render_gt(expr = input_dna)
  output$kit_contents      <- render_gt(expr = SQK.LSK114.contents)
  output$flowcell_check    <- render_gt(expr = flowcell_check)
  output$rxn_adapter       <- render_gt(expr = rxn_adapter)
  output$rxn_endprep       <- render_gt(expr = rxn_endprep)
  output$rxn_flowcell      <- render_gt(expr = rxn_flowcell)
  
  output$LSK114_tubes <- renderImage({list(src = "attachments/SQK-LSK114_tubes.svg", height = "90%")}, deleteFile = FALSE) 
  
steps <- paste0("step", 1:38)

for (step in steps) {
  local({step_id <- step 
    output[[paste0("text_", step_id)]] <- renderUI({ if (isTRUE(input[[paste0("annotate_", step_id)]])) {
        textAreaInput(inputId = paste0("note_", step_id), label = "Add note", placeholder = "Write something here...", rows = 4, width = "100%")}})

    output[[paste0("submit_", step_id)]] <- renderUI({ if (isTRUE(input[[paste0("annotate_", step_id)]])) {
        actionButton(inputId = paste0("submit_", step_id), label = "Submit note")}})
  
    n_annotations <- count()
  })}
   
  
  
}
```

```{r}
shinyApp(ui = ui, server = server)
```

