# endprep_steps.R
endprep <- list(
  list("Thaw DNA Control Sample (DCS) at room temperature, spin down, mix by pipetting, and place on ice."),
  list("Prepare the NEB reagents in accordance with manufacturer’s instructions, and place on ice.",
       a = "Thaw all reagents on ice.",
       b = "Flick and/or invert the reagent tubes to ensure they are well mixed. Do not vortex the FFPE DNA Repair Mix or Ultra II End Prep Enzyme Mix.",
       c = "Always spin down tubes before opening for the first time each day.",
       d = "Vortex the FFPE DNA Repair Buffer v2, or the NEBNext FFPE DNA Repair Buffer and Ultra II End Prep Reaction Buffer to ensure they are well mixed.",
       e = "The FFPE DNA Repair Buffer may have a yellow tinge and is fine to use if yellow."),
  list("Prepare the DNA in nuclease-free water according to the values in the table below.",
       a = "Transfer the 'Extract to add' volume into a 1.5 ml Eppendorf DNA LoBind tube.",
       b = "Add nuclease-free water according to the volume under 'H2O to add' to reach the total volume.",
       c = "Check each row as you go to keep track of progress.",
       d = "Mix thoroughly by pipetting up and down, or by flicking the tube.",
       e = "Spin down briefly in a microfuge."),
  list("In a 0.2 ml thin-walled PCR tube, prepare the reaction mix."),
  list("Thoroughly mix the reaction by gently pipetting and briefly spinning down."),
  list("Using a thermal cycler, incubate at 20°C for 5 minutes and 65°C for 5 minutes."),
  list("Resuspend the AMPure XP Beads (AXP) by vortexing."),
  list("Transfer the DNA sample to a clean 1.5 ml Eppendorf DNA LoBind tube."),
  list("Add 60 µl of resuspended the AMPure XP Beads (AXP) to the end-prep reaction and mix by flicking the tube."),
  list("Incubate on a Hula mixer (rotator mixer) for 5 minutes at room temperature."),
  list("Prepare 500 μl of fresh 80% ethanol in nuclease-free water."),
  list("Spin down the sample and pellet on a magnet until supernatant is clear and colourless. Keep the tube on the magnet, and pipette off the supernatant."),
  list("Keep the tube on the magnet and wash the beads with 200 µl of freshly prepared 80% ethanol without disturbing the pellet. Remove the ethanol using a pipette and discard."),
  list("Repeat the previous step."),
  list("Spin down and place the tube back on the magnet. Pipette off any residual ethanol. Allow to dry for ~30 seconds, but do not dry the pellet to the point of cracking."),
  list("Remove the tube from the magnetic rack and resuspend the pellet in 61 µl nuclease-free water. Incubate for 2 minutes at room temperature."),
  list("Pellet the beads on a magnet until the eluate is clear and colourless, for at least 1 minute."),
  list("Remove and retain 61 µl of eluate into a clean 1.5 ml Eppendorf DNA LoBind tube."),
  list("Quantify 1 µl of eluted sample using a Qubit fluorometer. Enter the QC results for each library below before proceeding.")) %>%
  set_names(paste0("I.", seq_along(.), "."))

endprep.recs <- accordion_panel(
  "Recommendations", 
  card(class = "bg-info",
       card_header("ONT's QC Recommendation"),
       card_body(tags$ul(
         tags$li("Samples with a wide distribution of fragment sizes, e.g. gDNA: Start with 1 μg of material for the Ligation Sequencing Kit, or 400 ng of material for the Rapid Sequencing Kit."),
         tags$li("Short fragment libraries, e.g. amplicons or cDNA: Start with 100-200 fmol."),
         tags$li("Some kits which have a PCR step included as part of the protocol can be used with lower DNA inputs: Refer to individual library prep protocols for details.")))),
  card(class = "bg-info",
       card_header("Tip from ONT"),
       card_body("ONT recommends using the NEBNext® Companion Module v2 for Oxford Nanopore Technologies® Ligation Sequencing (E7672S/E7672L), which contains all the NEB reagents needed for use with the Ligation Sequencing Kit."),
       card_footer("The previous version, NEBNext® Companion Module for Oxford Nanopore Technologies® Ligation Sequencing (NEB, E7180S/E7180L) is also compatible, but the recommended v2 module offers more efficient dA-tailing and ligation.")), 
  card(class = "bg-info",
       card_header("Tip from ONT"),
       card_body("ONT recommends using the DNA Control Sample (DCS) in your library prep for troubleshooting purposes."),
       card_footer("You can also omit this step and make up the extra 1 µl with your sample DNA, if preferred.")), 
  card(class = "bg-primary",
       card_header("Check your flow cell."),
       card_body("You should perform a flow cell check before starting your library prep to ensure you have a flow cell with enough pores for a good sequencing run.",
                 accordion(open = FALSE, accordion_panel(title = "Flow Cell Guidelines", gt_output("flowcell_check"))))))