library(knitr)
library(tinytex)
source(paste0(params$local, "dependencies/options.R"))
library(bibtex)
library(BiocManager)
library(bookdown)
library(conflicted)
library(devtools)
library(dplyr)
library(fontawesome)
library(ggplot2)
library(ggpubr)
library(ggsci)
library(glue)
library(gt)
library(gtExtras)
library(gtable)
library(htmltools)
library(kableExtra)
library(knitcitations)
library(leaflet)    # For interactive maps
library(lubridate)
library(magrittr)
library(MASS)
library(paletteer)
library(pandoc)
library(png)
library(purrr)
library(raster)     # For handling raster data (if needed for climate layers)
library(rcompanion)
library(readr) 
library(RefManageR)
library(rlang)
library(rmarkdown)
library(sf)         # For spatial data handling
library(shiny)
library(stringr)
library(tibble)
library(tidyr)
library(usethis)
library(utf8)
source(paste0(params$local, "dependencies/functions.R"))

library(lpSolve)
library(shinyMatrix)
library(akima)
library(fontawesome)
library(showtext)
library(scales)
library(ggnewscale)
library(ggtext)
library(bslib)
library(bsicons)

library(pander)
library(flexdashboard)
library(shinydashboard)
library(sass)

conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::left_join)
conflicts_prefer(dplyr::inner_join)
conflicts_prefer(dplyr::full_join)
conflicts_prefer(dplyr::semi_join)
conflicts_prefer(dplyr::rename)
conflicts_prefer(ggplot2::margin)
conflicts_prefer(ggplot2::theme_classic)
conflicts_prefer(ggplot2::ggplot)
conflicts_prefer(ggplot2::theme_minimal)
conflicts_prefer(ggplot2::aes)
conflicts_prefer(dplyr::lag)
conflicts_prefer(RefManageR::cite)
conflicts_prefer(shinydashboard::box)
conflicts_prefer(rlang::set_names)
conflicts_prefer(purrr::flatten)

font_add("fa-solid", paste0(params$local, "dependencies/fonts/Font Awesome 6 Free-Solid-900.otf"))
showtext_auto()
