
```{r}
supplies <- bind_rows(
  tibble(
    Step = rep("All", 7),
    Category = rep("Equipment", 7),
    Item = c("MinION Device",
             "Qubit fluorometer",
             "Thermal cycler",
             "Hula mixer",
             "Magnetic rack",
             "Microfuge",
             "Ice bucket or freezy block"),
    Manufacturer = c("ONT", "Invitrogen", rep("NA", 5)),
    Catalog = rep("NA", 7)
  ),
  tibble(
    Step = rep("All", 2),
    Category = rep("Kit", 2),
    Item = c("Ligation Sequencing Kit V14", "NEBNext Companion Module v2 for ONT Ligation Sequencing"),
   Manufacturer = c("ONT", "NEB"),
      Catalog = c("SQK-LSK114", "E7672S")
  ),
  tibble(Step     = c("End_Prep"),
    Category = c("Other"),
    Item = c("1 µg (or 100-200 fmol) high molecular weight genomic DNA"),
    Manufacturer = c("NA"),
    Catalog = c("NA")),
    
  tibble(Step     = rep("End_Prep", 10),
    Category = rep("Materials", 10),
    Item = c("DNA Control Sample",
             "AMPure XP Beads",
             "NEBNext® FFPE DNA Repair Buffer v2",
             "NEBNext® Ultra II End Prep Enzyme Mix",
             "Qubit dsDNA HS Assay Kit",
             "Nuclease-free water",
             "Freshly prepared 80% ethanol in nuclease-free water",
             "Qubit™ Assay Tubes",
             "0.2 ml thin-walled PCR tubes",
             "1.5 ml Eppendorf DNA LoBind tubes"),
    Manufacturer = c("ONT", "ONT", "NEB", "NEB", "Invitrogen", "Any", "Any", "Invitrogen", "Any", "Any"),
    Catalog = c("NA", "NA", "E7672S/M6630", "E7672S/E7363", "Q32851", "NA", "NA", "Q32856", "NA", "NA")),
  tibble(
    Step     = rep("Adapter_Ligation", 4),
    Category = rep("Materials", 4),
    Item  = c("Ligation Adapter (LA)",
                 "Ligation Buffer (LNB)",
                 "Long Fragment Buffer (LFB)",
                 "Short Fragment Buffer (SFB)"), 
    Manufacturer = rep("ONT", 4),
    Catalog = rep("NA", 4)),
  tibble(
    Step     = rep("Adapter_Ligation", 2),
    Category = rep("Consumables", 2),
    Item  = c("Salt-T4® DNA Ligase",
                 "1.5 ml Eppendorf DNA LoBind tubes"),
    Manufacturer = c("NEB",
                     "Any"),
    Catalog = c("M0467",
                "NA")),
  tibble(
    Step    = rep("Library_Cleanup", 2),
    Category = rep("Materials", 2),
    Item = c("AMPure XP Beads (AXP)",
                "Elution Buffer (EB)"), 
    Manufacturer = rep("ONT", 2),
    Catalog = rep("NA", 2)),
  tibble(
    Step    = rep("Library_Cleanup", 3),
    Category = rep("Consumables", 3),
    Item = c("1.5 ml Eppendorf DNA LoBind tubes",
                "Qubit dsDNA HS Assay Kit",
                "Qubit™ Assay Tubes"),
    Manufacturer = c("Any",
                     "Invitrogen",
                     "Invitrogen"),
    Catalog = c("NA",
                "Q32851",
                "Q32856")),
  tibble(
    Step    = rep("Load_Flowcell", 5),
    Category = rep("Materials", 5),
    Item = c("Flow Cell Flush (FCF)",
             "Flow Cell Tether (FCT)",
             "Library Solution (LIS)",
             "Library Beads (LIB)",
             "Sequencing Buffer (SB)"),
    Manufacturer = rep("ONT", 5),
    Catalog = rep("NA", 5)),
  tibble(
    
    Step    = rep("Load_Flowcell", 3),
    Category = rep("Consumables", 3),
    Item     = c("MinION Flow Cell",
                 "Bovine Serum Albumin (BSA) (50 mg/ml)",
                 "1.5 ml Eppendorf DNA LoBind tubes"),
    Manufacturer = c("ONT", rep("Any", 2)),
    Catalog = rep("NA", 3)
    )
) %>%
  mutate(Category = factor(Category, levels = c("Equipment", "Kit", "Materials", "Consumables", "Other"), ordered = T),
         Step     = factor(Step, levels = c("All", "End_Prep", "Adapter_Ligation", "Library_Cleanup", "Load_Flowcell"), ordered = T)) %>%
  arrange(Step, Category, Manufacturer)
```


```{r}
gt_supplies <- supplies %>% 
  mutate(Manufacturer = if_else(Manufacturer == "NA", "", Manufacturer),
         Catalog      = if_else(Catalog      == "NA", "", Catalog)) %>%
  arrange(Step, Category) %>%
  mutate(Category = if_else(lag(Step) != Step | lag(Category) != Category | row_number() == 1, Category, "")) %>%
  mutate(Step = case_when(Step == "All" ~ "Multiple Steps",
                          Step == "End_Prep" ~ "1. DNA Repair and End Prep",
                          Step == "Adapter_Ligation" ~ "2. Adapter Ligation",
                          Step == "Library_Cleanup" ~ "3. Library Clean-Up",
                          Step == "Load_Flowcell" ~ "4. Prime and Load the Flow Cell")) %>%
  gt(groupname_col = "Step", rowname_col = "Category") %>%
  cols_label(Item ~ "",
             Manufacturer ~ "",
             Catalog ~ "") %>%
  tab_header("Overview of Supplies Needed") %>%
  tab_style(style = cell_text(align = "left"), locations = cells_title()) %>%
  tab_style(style = cell_text(weight = "bold", transform = "uppercase"), locations = cells_row_groups()) %>%
  tab_stub_indent(rows = everything(), indent = 3) %>%
  tab_style(style = cell_text(weight = "bold", transform = "uppercase"), locations = cells_stub()) %>%
  opt_stylize(6, "pink")
```

```{r}
supplies_endprep <- supplies %>% filter(Step == "End_Prep") %>%
  select(-Step) %>%
  mutate(Manufacturer = if_else(Manufacturer == "NA" | Manufacturer == "Any", "", Manufacturer),
         Catalog      = if_else(Catalog      == "NA" | Catalog == "Any", "", Catalog)) %>%
  gt(groupname_col = "Category") %>%
  cols_label(Item ~ "",
             Manufacturer ~ "",
             Catalog ~ "") %>%
  tab_header("Materials & Supplies", subtitle = "DNA Repair & End Prep") %>%
  tab_style(style = cell_text(align = "left"), locations = cells_title()) %>%
  tab_style(style = cell_text(weight = "bold", transform = "uppercase"), locations = cells_row_groups()) %>%
  tab_style(style = cell_text(indent = 25), locations = cells_body(columns = "Item")) %>%
  opt_stylize(6, "pink")
```

```{r}
supplies_adapter <- supplies %>% filter(Step == "Adapter_Ligation") %>%
  select(-Step) %>%
  mutate(Manufacturer = if_else(Manufacturer == "NA" | Manufacturer == "Any", "", Manufacturer),
         Catalog      = if_else(Catalog      == "NA" | Catalog == "Any", "", Catalog)) %>%
  gt(groupname_col = "Category") %>%
  cols_label(Item ~ "",
             Manufacturer ~ "",
             Catalog ~ "") %>%
  tab_header("Materials & Supplies", subtitle = "Adapter Ligation") %>%
  tab_style(style = cell_text(align = "left"), locations = cells_title()) %>%
  tab_style(style = cell_text(weight = "bold", transform = "uppercase"), locations = cells_row_groups()) %>%
  tab_style(style = cell_text(indent = 25), locations = cells_body(columns = "Item")) %>%
  tab_footnote("Although third-party ligase products may be supplied with their own buffer, the ligation efficiency of the Ligation Adapter (LA) is higher when using the Ligation Buffer (LNB) supplied in the Ligation Sequencing Kit.",
               locations = cells_body(columns = Item, rows = Item == "Ligation Buffer (LNB)")) %>%
  tab_footnote("ONT recommends using the Salt-T4® DNA Ligase (NEB, M0467). Salt-T4® DNA Ligase (NEB, M0467) can be bought separately or is provided in the NEBNext® Companion Module v2 for Oxford Nanopore Technologies® Ligation Sequencing (catalogue number E7672S or E7672L). The Quick T4 DNA Ligase (NEB, E6057) available in the previous version NEBNext® Companion Module for Oxford Nanopore Technologies® Ligation Sequencing (NEB, E7180S or E7180L) is also compatible, but the new recommended reagent offers more efficient ligation.",
               locations = cells_body(columns = Item, rows = Item == "Salt-T4® DNA Ligase")) %>%
  opt_stylize(6, "pink")
```

```{r}
supplies_cleanup <- supplies %>% filter(Step == "Library_Cleanup") %>%
  select(-Step) %>%
  mutate(Manufacturer = if_else(Manufacturer == "NA" | Manufacturer == "Any", "", Manufacturer),
         Catalog      = if_else(Catalog      == "NA" | Catalog == "Any", "", Catalog)) %>%
  gt(groupname_col = "Category") %>%
  cols_label(Item ~ "",
             Manufacturer ~ "",
             Catalog ~ "") %>%
  tab_header("Materials & Supplies", subtitle = "Library Clean-Up") %>%
  tab_style(style = cell_text(align = "left"), locations = cells_title()) %>%
  tab_style(style = cell_text(weight = "bold", transform = "uppercase"), locations = cells_row_groups()) %>%
  tab_style(style = cell_text(indent = 25), locations = cells_body(columns = "Item")) %>%
  opt_stylize(6, "pink")
```

```{r}
supplies_flowcell <- supplies %>% filter(Step == "Load_Flowcell") %>%
  select(-Step) %>%
  mutate(Manufacturer = if_else(Manufacturer == "NA" | Manufacturer == "Any", "", Manufacturer),
         Catalog      = if_else(Catalog      == "NA" | Catalog == "Any", "", Catalog)) %>%
  gt(groupname_col = "Category") %>%
  cols_label(Item ~ "",
             Manufacturer ~ "",
             Catalog ~ "") %>%
  tab_header("Materials & Supplies", subtitle = "Priming & Loading the Flow Cell") %>%
  tab_style(style = cell_text(align = "left"), locations = cells_title()) %>%
  tab_style(style = cell_text(weight = "bold", transform = "uppercase"), locations = cells_row_groups()) %>%
  tab_style(style = cell_text(indent = 25), locations = cells_body(columns = "Item")) %>%
  tab_footnote("Please note, this kit is only compatible with R10.4.1 flow cells (FLO-MIN114).", 
               locations = cells_body(columns = Item, rows = Item == "MinION Flow Cell")) %>%
  tab_footnote("For optimal sequencing performance and improved output on MinION R10.4.1 flow cells (FLO-MIN114), ONT recommends adding Bovine Serum Albumin (BSA) to the flow cell priming mix at a final concentration of 0.2 mg/ml.", 
               locations = cells_body(columns = Item, rows = Item == "Bovine Serum Albumin (BSA) (50 mg/ml)")) %>%
  opt_stylize(6, "pink")
```

```{r}
input_dna <- tibble(
  min_kb = c(0, 1, 10),
  max_kb = c(1, 10, 100),
  input  = c("200 fmol",
             "100-200 fmol",
             "1 ug")) %>%
gt() %>%
  tab_header(title = "Input DNA Amounts") %>%
  cols_label(min_kb ~ "Length of Target",
             input  ~ "Template Needed") %>%
  cols_merge(columns = c("min_kb", "max_kb"),
             pattern = "{1} kb - {2} kb") %>%
  fmt_units(columns = everything()) %>%
  cols_align("left", columns = everything()) %>%
  tab_style(locations = cells_title(), style = list(
                                              cell_text(align = "left",
                                                         size = "medium"))) %>%
  opt_stylize(4, color = "cyan") %>%
  tab_source_note("Note: If the library yields are below the input recommendations, load the entire library.") %>%
  tab_source_note(md("If required, use a mass to mol calculator such as the [NEB calculator](https://nebiocalculator.neb.com/#!/dsdnaamt).")) %>%
  tab_source_note("The prepared library is used for loading into the flow cell.")
```


```{r}
SQK.LSK114.contents <- tibble(
    abbrev  = c("DCS", "LA", "LNB", "LFB", "SFB", "AXP", "SB", "EB", "LIB", "LIS", "FCF", "FCT"),
    reagent = c("DNA Control Strand", "Ligation Adapter", "Ligation Buffer", "Long Fragment Buffer", "Short Fragment Buffer", "AMPure XP Beads", "Sequencing Buffer", "Elution Buffer", "Library Beads", "Library Solution", "Flow Cell Flush", "Flow Cell Tether"),
    color   = c("yellow", "green", "lightgray", "orange", "gray", "brown", "red", "black", "magenta", "pink", "blue", "purple")
  ) %>%
gt() %>%
  tab_header("SQK-LSK114 Contents") %>%
  tab_style_body(style   = cell_fill(color = from_column("color")),
                 columns = "abbrev",
                 pattern = ".") %>%
  cols_label(abbrev ~ "", reagent ~ "") %>%
  cols_hide(color) %>%
  opt_table_lines("none") %>%
  tab_style(locations = cells_title(), style = cell_text(align = "left", size = "medium")) %>%
  opt_horizontal_padding(1.5)
```

```{r}
rxn_end_repair <- tibble(
  Reagent = c("Prepared DNA (from previous step)", 
              "DNA CS (optional)",
              "NEBNext FFPE DNA Repair Buffer v2",
              "NEBNext FFPE DNA Repair Mix ",
              "Ultra II End-prep Enzyme Mix"),
  Volume_ul = c(47, 1, 7, 2, 3)
) %>%
gt(rowname_col = "Reagent") %>%
  cols_label(Volume_ul ~ "Vol ({{uL}})") %>%
  grand_summary_rows(fns = list(label = "Total", id = "total", fn = "sum"), side = "bottom") %>%
  tab_header("In a 0.2 ml thin-walled PCR tube, mix the following:") %>%
  tab_style(style = list(
    cell_text(align = "left"),
    cell_borders(sides = "top")), 
    locations = cells_title()) %>%
  tab_source_note("Between each addition, pipette mix 10-20 times.") %>%
  tab_source_note("Then thoroughly mix the reaction by gently pipetting and briefly spinning down.") %>%
  opt_stylize(style = 1, color = "cyan")
```

```{r}
rxn_adapter <- tibble(
  Reagent = c("DNA sample from the previous step",
              "Ligation Adapter (LA)",
              "Ligation Buffer (LNB)",
              "Salt-T4® DNA Ligase"),
  Volume_ul = c(60, 5, 25, 10)
) %>%
gt(rowname_col = "Reagent") %>%
  cols_label(Volume_ul ~ "Vol ({{uL}})") %>%
  grand_summary_rows(fns = list(label = "Total", id = "total", fn = "sum"), side = "bottom") %>%
  tab_header("In a 1.5 ml Eppendorf DNA LoBind tube, mix in the following order:") %>%
  tab_style(style = list(
    cell_text(align = "left"),
    cell_borders(sides = "top")), 
    locations = cells_title()) %>%
  tab_source_note("Between each addition, pipette mix 10-20 times.") %>%
  opt_stylize(style = 1, color = "cyan")
```

```{r}
rxn_flowcell_prime <- tibble(
  Reagent = c("Flow Cell Flush (FCF)",
              "Bovine Serum Albumin (BSA) at 50 mg/ml",
              "Flow Cell Tether (FCT)"),
  Volume_ul = c(1170, 5, 30)
) %>%
gt(rowname_col = "Reagent") %>%
  cols_label(Volume_ul ~ "Vol ({{uL}}) per Flow Cell") %>%
  grand_summary_rows(fns = list(label = "Total", id = "total", fn = "sum"), side = "bottom") %>%
  tab_header("In a suitable tube for the number of flow cells, combine the following reagents:") %>%
  tab_style(style = list(
    cell_text(align = "left"),
    cell_borders(sides = "top")), 
    locations = cells_title()) %>%
  tab_source_note("Mix by pipetting at room temperature.") %>%
  opt_stylize(style = 1, color = "cyan")

```

```{r}
flowcell_check <- tibble(
  flow_cell = c("Flongle",
                "MinION",
                "PromethION"),
  min_pores = c(50, 800, 5000)) %>%
  gt() %>%
  tab_header(title = "Optional: Complete a flow cell check to assess the number of pores available before loading the library.") %>%
  cols_label(flow_cell ~ "Flow Cell Version",
             min_pores ~ "Minimum Pores Needed") %>%
  cols_align("left", columns = everything()) %>%
  tab_style(locations = cells_title(), style = list(
                                              cell_text(align = "left",
                                                         size = "medium"))) %>%
  tab_source_note(md("*This step can be omitted if the flow cell has been checked previously.*")) %>%
  opt_stylize(2, color = "cyan")
```
