output$LSK114_tubes <- renderImage({list(src = "attachments/SQK-LSK114_tubes.svg", height = "90%")}, deleteFile = FALSE) 
output$imgIV3a      <- renderImage({list(src="attachments/Flow_Cell_Loading_Diagrams_Step_1a.svg"    , height = "90%")}, deleteFile = FALSE)
output$imgIV3b      <- renderImage({list(src="attachments/Flow_Cell_Loading_Diagrams_Step_1b.svg"    , height = "75%")}, deleteFile = FALSE)
output$imgIV4       <- renderImage({list(src="attachments/Flow_Cell_Loading_Diagrams_Step_2.svg"     , height = "75%")}, deleteFile = FALSE)
output$imgIV5       <- renderImage({list(src="attachments/Flow_Cell_Loading_Diagrams_Step_03_V5.gif" , height = "75%")}, deleteFile = FALSE)
output$imgIV6       <- renderImage({list(src="attachments/Flow_Cell_Loading_Diagrams_Step_04_V5.gif" , height = "75%")}, deleteFile = FALSE)
output$imgIV9a      <- renderImage({list(src="attachments/Flow_Cell_Loading_Diagrams_Step_06_V5.gif" , height = "75%")}, deleteFile = FALSE)
output$imgIV11      <- renderImage({list(src="attachments/Flow_Cell_Loading_Diagrams_Step_07_V5.gif" , height = "75%")}, deleteFile = FALSE)
output$imgIV12a     <- renderImage({list(src="attachments/Step_8_update.png"                         , height = "75%")}, deleteFile = FALSE)
output$imgIV12b     <- renderImage({list(src="attachments/Flow_Cell_Loading_Diagrams_Step_9.svg"     , height = "75%")}, deleteFile = FALSE)
output$imgIV13      <- renderImage({list(src="attachments/J2264_-_Light_shield_animation_Flow_Cell_FAW_optimised.gif", height = "75%")}, deleteFile = FALSE)
